### ISSUE TITLE
with() method

### ISSUE THREAD

**Issue by shimsag** [hi019/laravel-scout-typesense#1]
Thank you so much for this fork!!

Can you also implement the with() method so we can include the facet filters in our search results?

**Comment by hi019** [comment]
Hi, can you explain a bit more? What do you mean by the `with` method?

**Comment by shimsag** [comment]
Thank you for the quick response.
I would like to grab the facet filters with their counts, in addition to the eloquent models..

Algolia users have an option for that using a with() method (see below link).
https://www.algolia.com/doc/framework-integration/laravel/searching/server-side-search/?client=php#search-with-custom-search-parameters

**Comment by hi019** [comment]
I don't plan to implement this feature myself, as this package is mainly intended to cover my own needs. But I would consider a PR!

**Comment by hi019** [comment]
I'll be deprecating this package in favour of https://github.com/typesense/laravel-scout-typesense-engine
